### ISSUE TITLE
CI jobs run when code is merged

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1087]
I just noticed that CI jobs run both when a pull request is being made and when code is merged/pushed into the main branch. This seems like duplicate effort. If there's a reason then lets mention it for later.

From `.github/workflows/ci.yml`
```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```
