### ISSUE TITLE
Ubuntu 'xenial': InRelease file is expired

### ISSUE THREAD

**Issue by jlettman** [systemd/mkosi#314]
Builds with Ubuntu 'xenial' fail to build due to a signature expiration on the InRelease file on the official mirror:

**mkosi version:** 4
**debootstrap error:** `E: InRelease file http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease is expired since (Tue, 08 Jan 2019 00:00:00 -0500)`

The image I am building with `mkosi` requires the 'xenial' release. 
Is there an issue with my environment or is there a method to ignore expired `InRelease` files?

### Command
`sudo mkosi -d ubuntu -r xenial -t directory`

### Output
```
DISTRIBUTION:
          Distribution: ubuntu
               Release: xenial
                Mirror: http://archive.ubuntu.com/ubuntu

OUTPUT:
         Output Format: directory
                Output: /home/jlettman/test-ubuntu-xenial/image
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: no
            Encryption: no
                Verity: no

PACKAGES:
              Packages: none
         Package Cache: none
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /home/jlettman/test-ubuntu-xenial
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /home/jlettman/test-ubuntu-xenial/.mkosi-8h2bnkrm complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /home/jlettman/test-ubuntu-xenial/.mkosi-128l5wwd is now set up.
‣ Setting up basic OS tree...
‣ Setting up basic OS tree complete.
‣ Mounting Package Cache...
‣ Mounting Package Cache complete.
‣ Installing Ubuntu...
I: Retrieving InRelease 
E: InRelease file http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease is expired since (Tue, 08 Jan 2019 00:00:00 -0500)
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4486, in <module>
    main()
  File "/usr/bin/mkosi", line 4482, in main
    run_verb(args)
  File "/usr/bin/mkosi", line 4452, in run_verb
    build_stuff(args)
  File "/usr/bin/mkosi", line 4281, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False, cleanup=True)
  File "/usr/bin/mkosi", line 4107, in build_image
    run_build_script=run_build_script, cached=cached)
  File "/usr/bin/mkosi", line 1952, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1680, in install_ubuntu
    install_debian_or_ubuntu(args, workspace, run_build_script=run_build_script, mirror=args.mirror)
  File "/usr/bin/mkosi", line 1596, in install_debian_or_ubuntu
    run(cmdline, check=True)
  File "/usr/bin/mkosi", line 69, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', '--merged-usr', 'xenial', '/home/jlettman/test-ubuntu-xenial/.mkosi-128l5wwd/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 1.
```

## Workaround attempt
(fails similar to above; skipping output for brevity)

Following advice noted elsewhere for `apt`, I applied a workaround through the skeleton directory; however, this appears to have no impact.

Similarly, this workaround was also applied to the machine invoking `mkosi`.

### Commands
```bash
mkdir -p mkosi.skeleton/etc/apt/apt.conf.d; 
echo Acquire::Check-Valid-Until=false >mkosi.skeleton/etc/apt/apt.conf.d/10-no-check-valid-until; 
sudo mkosi -d ubuntu -r xenial -t directory;
```

**Comment by jlettman** [comment]
Using `libfaketime`, I tried to change the date. The result is the same, however the "expired since" portion changes to reflect the current environment view of the new time.

**Command:** `sudo faketime 'last year' mkosi -d ubuntu -r xenial -t directory`
**New error:** `E: InRelease file http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease is expired since (Mon, 08 Jan 2018 00:00:00 -0500)`

**Comment by jlettman** [comment]
Manually executing the `debootstrap` command `mkosi` uses, with `--no-check-valid-until` resolves the error.

Relevant line: https://github.com/systemd/mkosi/blob/master/mkosi#L1578

**Comment by jlettman** [comment]
Inserting `--no-check-valid-until` on the `cmdline` array yields the desired result. I'll make a PR, but I'm personally unsure if using the argument universally is the appropriate long-term solution.

Here's my branch with the fix:

## Command
`sudo ~/repos/mkosi/mkosi -d ubuntu -r xenial -t directory`

## Output
```
DISTRIBUTION:
          Distribution: ubuntu
               Release: xenial
                Mirror: http://archive.ubuntu.com/ubuntu

OUTPUT:
         Output Format: directory
                Output: /home/jlettman/test-mkosi-ubuntu/image
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: no
            Encryption: no
                Verity: no

PACKAGES:
              Packages: none
         Package Cache: none
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /home/jlettman/test-mkosi-ubuntu
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /home/jlettman/test-mkosi-ubuntu/.mkosi-jluhaqrh complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /home/jlettman/test-mkosi-ubuntu/.mkosi-o3vpdaqo is now set up.
‣ Setting up basic OS tree...
‣ Setting up basic OS tree complete.
‣ Mounting Package Cache...
‣ Mounting Package Cache complete.
‣ Installing Ubuntu...
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id 790BC7277767219C42C86F933B4FE6ACC0B21F32)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://archive.ubuntu.com/ubuntu...
I: Retrieving adduser 3.113+nmu3ubuntu4
I: Validating adduser 3.113+nmu3ubuntu4
I: Retrieving apt 1.2.10ubuntu1
I: Validating apt 1.2.10ubuntu1
I: Retrieving base-files 9.4ubuntu4
I: Validating base-files 9.4ubuntu4
I: Retrieving base-passwd 3.5.39
I: Validating base-passwd 3.5.39
I: Retrieving bash 4.3-14ubuntu1
I: Validating bash 4.3-14ubuntu1
I: Retrieving bsdutils 1:2.27.1-6ubuntu3
I: Validating bsdutils 1:2.27.1-6ubuntu3
I: Retrieving coreutils 8.25-2ubuntu2
I: Validating coreutils 8.25-2ubuntu2
I: Retrieving dash 0.5.8-2.1ubuntu2
I: Validating dash 0.5.8-2.1ubuntu2
I: Retrieving debconf 1.5.58ubuntu1
I: Validating debconf 1.5.58ubuntu1
I: Retrieving debianutils 4.7
I: Validating debianutils 4.7
I: Retrieving diffutils 1:3.3-3
I: Validating diffutils 1:3.3-3
I: Retrieving dpkg 1.18.4ubuntu1
I: Validating dpkg 1.18.4ubuntu1
I: Retrieving e2fslibs 1.42.13-1ubuntu1
I: Validating e2fslibs 1.42.13-1ubuntu1
I: Retrieving e2fsprogs 1.42.13-1ubuntu1
I: Validating e2fsprogs 1.42.13-1ubuntu1
I: Retrieving findutils 4.6.0+git+20160126-2
I: Validating findutils 4.6.0+git+20160126-2
I: Retrieving gcc-5-base 5.3.1-14ubuntu2
I: Validating gcc-5-base 5.3.1-14ubuntu2
I: Retrieving gcc-6-base 6.0.1-0ubuntu1
I: Validating gcc-6-base 6.0.1-0ubuntu1
I: Retrieving gnupg 1.4.20-1ubuntu3
I: Validating gnupg 1.4.20-1ubuntu3
I: Retrieving gpgv 1.4.20-1ubuntu3
I: Validating gpgv 1.4.20-1ubuntu3
I: Retrieving grep 2.24-1
I: Validating grep 2.24-1
I: Retrieving gzip 1.6-4ubuntu1
I: Validating gzip 1.6-4ubuntu1
I: Retrieving hostname 3.16ubuntu2
I: Validating hostname 3.16ubuntu2
I: Retrieving init 1.29ubuntu1
I: Validating init 1.29ubuntu1
I: Retrieving init-system-helpers 1.29ubuntu1
I: Validating init-system-helpers 1.29ubuntu1
I: Retrieving initscripts 2.88dsf-59.3ubuntu2
I: Validating initscripts 2.88dsf-59.3ubuntu2
I: Retrieving insserv 1.14.0-5ubuntu3
I: Validating insserv 1.14.0-5ubuntu3
I: Retrieving libacl1 2.2.52-3
I: Validating libacl1 2.2.52-3
I: Retrieving libapparmor1 2.10.95-0ubuntu2
I: Validating libapparmor1 2.10.95-0ubuntu2
I: Retrieving libapt-pkg5.0 1.2.10ubuntu1
I: Validating libapt-pkg5.0 1.2.10ubuntu1
I: Retrieving libattr1 1:2.4.47-2
I: Validating libattr1 1:2.4.47-2
I: Retrieving libaudit-common 1:2.4.5-1ubuntu2
I: Validating libaudit-common 1:2.4.5-1ubuntu2
I: Retrieving libaudit1 1:2.4.5-1ubuntu2
I: Validating libaudit1 1:2.4.5-1ubuntu2
I: Retrieving libblkid1 2.27.1-6ubuntu3
I: Validating libblkid1 2.27.1-6ubuntu3
I: Retrieving libbz2-1.0 1.0.6-8
I: Validating libbz2-1.0 1.0.6-8
I: Retrieving libc-bin 2.23-0ubuntu3
I: Validating libc-bin 2.23-0ubuntu3
I: Retrieving libc6 2.23-0ubuntu3
I: Validating libc6 2.23-0ubuntu3
I: Retrieving libcap2 1:2.24-12
I: Validating libcap2 1:2.24-12
I: Retrieving libcap2-bin 1:2.24-12
I: Validating libcap2-bin 1:2.24-12
I: Retrieving libcomerr2 1.42.13-1ubuntu1
I: Validating libcomerr2 1.42.13-1ubuntu1
I: Retrieving libcryptsetup4 2:1.6.6-5ubuntu2
I: Validating libcryptsetup4 2:1.6.6-5ubuntu2
I: Retrieving libdb5.3 5.3.28-11
I: Validating libdb5.3 5.3.28-11
I: Retrieving libdebconfclient0 0.198ubuntu1
I: Validating libdebconfclient0 0.198ubuntu1
I: Retrieving libdevmapper1.02.1 2:1.02.110-1ubuntu10
I: Validating libdevmapper1.02.1 2:1.02.110-1ubuntu10
I: Retrieving libfdisk1 2.27.1-6ubuntu3
I: Validating libfdisk1 2.27.1-6ubuntu3
I: Retrieving libgcc1 1:6.0.1-0ubuntu1
I: Validating libgcc1 1:6.0.1-0ubuntu1
I: Retrieving libgcrypt20 1.6.5-2
I: Validating libgcrypt20 1.6.5-2
I: Retrieving libgpg-error0 1.21-2ubuntu1
I: Validating libgpg-error0 1.21-2ubuntu1
I: Retrieving libkmod2 22-1ubuntu4
I: Validating libkmod2 22-1ubuntu4
I: Retrieving liblz4-1 0.0~r131-2ubuntu2
I: Validating liblz4-1 0.0~r131-2ubuntu2
I: Retrieving liblzma5 5.1.1alpha+20120614-2ubuntu2
I: Validating liblzma5 5.1.1alpha+20120614-2ubuntu2
I: Retrieving libmount1 2.27.1-6ubuntu3
I: Validating libmount1 2.27.1-6ubuntu3
I: Retrieving libncurses5 6.0+20160213-1ubuntu1
I: Validating libncurses5 6.0+20160213-1ubuntu1
I: Retrieving libncursesw5 6.0+20160213-1ubuntu1
I: Validating libncursesw5 6.0+20160213-1ubuntu1
I: Retrieving libpam-modules 1.1.8-3.2ubuntu2
I: Validating libpam-modules 1.1.8-3.2ubuntu2
I: Retrieving libpam-modules-bin 1.1.8-3.2ubuntu2
I: Validating libpam-modules-bin 1.1.8-3.2ubuntu2
I: Retrieving libpam-runtime 1.1.8-3.2ubuntu2
I: Validating libpam-runtime 1.1.8-3.2ubuntu2
I: Retrieving libpam0g 1.1.8-3.2ubuntu2
I: Validating libpam0g 1.1.8-3.2ubuntu2
I: Retrieving libpcre3 2:8.38-3.1
I: Validating libpcre3 2:8.38-3.1
I: Retrieving libprocps4 2:3.3.10-4ubuntu2
I: Validating libprocps4 2:3.3.10-4ubuntu2
I: Retrieving libreadline6 6.3-8ubuntu2
I: Validating libreadline6 6.3-8ubuntu2
I: Retrieving libseccomp2 2.2.3-3ubuntu3
I: Validating libseccomp2 2.2.3-3ubuntu3
I: Retrieving libselinux1 2.4-3build2
I: Validating libselinux1 2.4-3build2
I: Retrieving libsemanage-common 2.3-1build3
I: Validating libsemanage-common 2.3-1build3
I: Retrieving libsemanage1 2.3-1build3
I: Validating libsemanage1 2.3-1build3
I: Retrieving libsepol1 2.4-2
I: Validating libsepol1 2.4-2
I: Retrieving libsmartcols1 2.27.1-6ubuntu3
I: Validating libsmartcols1 2.27.1-6ubuntu3
I: Retrieving libss2 1.42.13-1ubuntu1
I: Validating libss2 1.42.13-1ubuntu1
I: Retrieving libstdc++6 5.3.1-14ubuntu2
I: Validating libstdc++6 5.3.1-14ubuntu2
I: Retrieving libsystemd0 229-4ubuntu4
I: Validating libsystemd0 229-4ubuntu4
I: Retrieving libtinfo5 6.0+20160213-1ubuntu1
I: Validating libtinfo5 6.0+20160213-1ubuntu1
I: Retrieving libudev1 229-4ubuntu4
I: Validating libudev1 229-4ubuntu4
I: Retrieving libusb-0.1-4 2:0.1.12-28
I: Validating libusb-0.1-4 2:0.1.12-28
I: Retrieving libustr-1.0-1 1.0.4-5
I: Validating libustr-1.0-1 1.0.4-5
I: Retrieving libuuid1 2.27.1-6ubuntu3
I: Validating libuuid1 2.27.1-6ubuntu3
I: Retrieving locales 2.23-0ubuntu3
I: Validating locales 2.23-0ubuntu3
I: Retrieving login 1:4.2-3.1ubuntu5
I: Validating login 1:4.2-3.1ubuntu5
I: Retrieving lsb-base 9.20160110
I: Validating lsb-base 9.20160110
I: Retrieving makedev 2.3.1-93ubuntu1
I: Validating makedev 2.3.1-93ubuntu1
I: Retrieving mawk 1.3.3-17ubuntu2
I: Validating mawk 1.3.3-17ubuntu2
I: Retrieving mount 2.27.1-6ubuntu3
I: Validating mount 2.27.1-6ubuntu3
I: Retrieving multiarch-support 2.23-0ubuntu3
I: Validating multiarch-support 2.23-0ubuntu3
I: Retrieving ncurses-base 6.0+20160213-1ubuntu1
I: Validating ncurses-base 6.0+20160213-1ubuntu1
I: Retrieving ncurses-bin 6.0+20160213-1ubuntu1
I: Validating ncurses-bin 6.0+20160213-1ubuntu1
I: Retrieving passwd 1:4.2-3.1ubuntu5
I: Validating passwd 1:4.2-3.1ubuntu5
I: Retrieving perl-base 5.22.1-9
I: Validating perl-base 5.22.1-9
I: Retrieving procps 2:3.3.10-4ubuntu2
I: Validating procps 2:3.3.10-4ubuntu2
I: Retrieving readline-common 6.3-8ubuntu2
I: Validating readline-common 6.3-8ubuntu2
I: Retrieving sed 4.2.2-7
I: Validating sed 4.2.2-7
I: Retrieving sensible-utils 0.0.9
I: Validating sensible-utils 0.0.9
I: Retrieving systemd 229-4ubuntu4
I: Validating systemd 229-4ubuntu4
I: Retrieving systemd-sysv 229-4ubuntu4
I: Validating systemd-sysv 229-4ubuntu4
I: Retrieving sysv-rc 2.88dsf-59.3ubuntu2
I: Validating sysv-rc 2.88dsf-59.3ubuntu2
I: Retrieving sysvinit-utils 2.88dsf-59.3ubuntu2
I: Validating sysvinit-utils 2.88dsf-59.3ubuntu2
I: Retrieving tar 1.28-2.1
I: Validating tar 1.28-2.1
I: Retrieving tzdata 2016d-0ubuntu0.16.04
I: Validating tzdata 2016d-0ubuntu0.16.04
I: Retrieving ubuntu-keyring 2012.05.19
I: Validating ubuntu-keyring 2012.05.19
I: Retrieving util-linux 2.27.1-6ubuntu3
I: Validating util-linux 2.27.1-6ubuntu3
I: Retrieving zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Validating zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Chosen extractor for .deb packages: ar
I: Extracting adduser...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting bsdutils...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting debconf...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting findutils...
I: Extracting gcc-6-base...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting init...
I: Extracting init-system-helpers...
I: Extracting initscripts...
I: Extracting insserv...
I: Extracting libacl1...
I: Extracting libapparmor1...
I: Extracting libattr1...
I: Extracting libaudit-common...
I: Extracting libaudit1...
I: Extracting libblkid1...
I: Extracting libbz2-1.0...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting libcap2...
I: Extracting libcap2-bin...
I: Extracting libcomerr2...
I: Extracting libcryptsetup4...
I: Extracting libdb5.3...
I: Extracting libdebconfclient0...
I: Extracting libdevmapper1.02.1...
I: Extracting libfdisk1...
I: Extracting libgcc1...
I: Extracting libgcrypt20...
I: Extracting libgpg-error0...
I: Extracting libkmod2...
I: Extracting liblzma5...
I: Extracting libmount1...
I: Extracting libncurses5...
I: Extracting libncursesw5...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting libpcre3...
I: Extracting libprocps4...
I: Extracting libseccomp2...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting libsmartcols1...
I: Extracting libss2...
I: Extracting libsystemd0...
I: Extracting libtinfo5...
I: Extracting libudev1...
I: Extracting libustr-1.0-1...
I: Extracting libuuid1...
I: Extracting locales...
I: Extracting login...
I: Extracting lsb-base...
I: Extracting makedev...
I: Extracting mawk...
I: Extracting mount...
I: Extracting multiarch-support...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting passwd...
I: Extracting perl-base...
I: Extracting procps...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting systemd...
I: Extracting systemd-sysv...
I: Extracting sysv-rc...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting util-linux...
I: Extracting zlib1g...
I: Installing core packages...
I: Unpacking required packages...
I: Unpacking adduser...
I: Unpacking base-files...
I: Unpacking base-passwd...
I: Unpacking bash...
I: Unpacking bsdutils...
I: Unpacking coreutils...
I: Unpacking dash...
I: Unpacking debconf...
I: Unpacking debianutils...
I: Unpacking diffutils...
I: Unpacking dpkg...
I: Unpacking e2fslibs:amd64...
I: Unpacking e2fsprogs...
I: Unpacking findutils...
I: Unpacking gcc-6-base:amd64...
I: Unpacking grep...
I: Unpacking gzip...
I: Unpacking hostname...
I: Unpacking init...
I: Unpacking init-system-helpers...
I: Unpacking initscripts...
I: Unpacking insserv...
I: Unpacking libacl1:amd64...
I: Unpacking libapparmor1:amd64...
I: Unpacking libattr1:amd64...
I: Unpacking libaudit-common...
I: Unpacking libaudit1:amd64...
I: Unpacking libblkid1:amd64...
I: Unpacking libbz2-1.0:amd64...
I: Unpacking libc-bin...
I: Unpacking libc6:amd64...
I: Unpacking libcap2:amd64...
I: Unpacking libcap2-bin...
I: Unpacking libcomerr2:amd64...
I: Unpacking libcryptsetup4:amd64...
I: Unpacking libdb5.3:amd64...
I: Unpacking libdebconfclient0:amd64...
I: Unpacking libdevmapper1.02.1:amd64...
I: Unpacking libfdisk1:amd64...
I: Unpacking libgcc1:amd64...
I: Unpacking libgcrypt20:amd64...
I: Unpacking libgpg-error0:amd64...
I: Unpacking libkmod2:amd64...
I: Unpacking liblzma5:amd64...
I: Unpacking libmount1:amd64...
I: Unpacking libncurses5:amd64...
I: Unpacking libncursesw5:amd64...
I: Unpacking libpam-modules:amd64...
I: Unpacking libpam-modules-bin...
I: Unpacking libpam-runtime...
I: Unpacking libpam0g:amd64...
I: Unpacking libpcre3:amd64...
I: Unpacking libprocps4:amd64...
I: Unpacking libseccomp2:amd64...
I: Unpacking libselinux1:amd64...
I: Unpacking libsemanage-common...
I: Unpacking libsemanage1:amd64...
I: Unpacking libsepol1:amd64...
I: Unpacking libsmartcols1:amd64...
I: Unpacking libss2:amd64...
I: Unpacking libsystemd0:amd64...
I: Unpacking libtinfo5:amd64...
I: Unpacking libudev1:amd64...
I: Unpacking libustr-1.0-1:amd64...
I: Unpacking libuuid1:amd64...
I: Unpacking locales...
I: Unpacking login...
I: Unpacking lsb-base...
I: Unpacking makedev...
I: Unpacking mawk...
I: Unpacking mount...
I: Unpacking multiarch-support...
I: Unpacking ncurses-base...
I: Unpacking ncurses-bin...
I: Unpacking passwd...
I: Unpacking perl-base...
I: Unpacking procps...
I: Unpacking sed...
I: Unpacking sensible-utils...
I: Unpacking systemd...
I: Unpacking systemd-sysv...
I: Unpacking sysv-rc...
I: Unpacking sysvinit-utils...
I: Unpacking tar...
I: Unpacking tzdata...
I: Unpacking util-linux...
I: Unpacking zlib1g:amd64...
I: Configuring required packages...
I: Configuring gcc-6-base:amd64...
I: Configuring lsb-base...
I: Configuring sensible-utils...
I: Configuring ncurses-base...
I: Configuring libsemanage-common...
I: Configuring libaudit-common...
I: Configuring libc6:amd64...
I: Configuring libbz2-1.0:amd64...
I: Configuring libkmod2:amd64...
I: Configuring libgpg-error0:amd64...
I: Configuring libc-bin...
I: Configuring libseccomp2:amd64...
I: Configuring libapparmor1:amd64...
I: Configuring libdebconfclient0:amd64...
I: Configuring diffutils...
I: Configuring insserv...
I: Configuring libcomerr2:amd64...
I: Configuring libsepol1:amd64...
I: Configuring libgcc1:amd64...
I: Configuring libustr-1.0-1:amd64...
I: Configuring libsmartcols1:amd64...
I: Configuring libaudit1:amd64...
I: Configuring libtinfo5:amd64...
I: Configuring libudev1:amd64...
I: Configuring libss2:amd64...
I: Configuring base-passwd...
I: Configuring e2fslibs:amd64...
I: Configuring debianutils...
I: Configuring libgcrypt20:amd64...
I: Configuring libncursesw5:amd64...
I: Configuring libdb5.3:amd64...
I: Configuring zlib1g:amd64...
I: Configuring hostname...
I: Configuring multiarch-support...
I: Configuring mawk...
I: Configuring libcap2:amd64...
I: Configuring libpcre3:amd64...
I: Configuring base-files...
I: Configuring libselinux1:amd64...
I: Configuring findutils...
I: Configuring ncurses-bin...
I: Configuring libncurses5:amd64...
I: Configuring makedev...
I: Configuring libattr1:amd64...
I: Configuring liblzma5:amd64...
I: Configuring libcap2-bin...
I: Configuring libsystemd0:amd64...
I: Configuring libdevmapper1.02.1:amd64...
I: Configuring libsemanage1:amd64...
I: Configuring libacl1:amd64...
I: Configuring libprocps4:amd64...
I: Configuring bsdutils...
I: Configuring coreutils...
I: Configuring tar...
I: Configuring dpkg...
I: Configuring sed...
I: Configuring perl-base...
I: Configuring grep...
I: Configuring debconf...
I: Configuring tzdata...
I: Configuring gzip...
I: Configuring dash...
I: Configuring init-system-helpers...
I: Configuring sysvinit-utils...
I: Configuring sysv-rc...
I: Configuring libpam0g:amd64...
I: Configuring locales...
I: Configuring libpam-modules-bin...
I: Configuring bash...
I: Configuring libpam-modules:amd64...
I: Configuring libpam-runtime...
I: Configuring passwd...
I: Configuring login...
I: Configuring adduser...
I: Configuring libuuid1:amd64...
I: Configuring libblkid1:amd64...
I: Configuring libmount1:amd64...
I: Configuring libcryptsetup4:amd64...
I: Configuring mount...
I: Configuring libfdisk1:amd64...
I: Configuring initscripts...
I: Configuring util-linux...
I: Configuring e2fsprogs...
I: Configuring procps...
I: Configuring systemd...
I: Configuring systemd-sysv...
I: Configuring init...
I: Configuring libc-bin...
I: Unpacking the base system...
I: Unpacking apt...
I: Unpacking gcc-5-base:amd64...
I: Unpacking gnupg...
I: Unpacking gpgv...
I: Unpacking libapt-pkg5.0:amd64...
I: Unpacking liblz4-1:amd64...
I: Unpacking libreadline6:amd64...
I: Unpacking libstdc++6:amd64...
I: Unpacking libusb-0.1-4:amd64...
I: Unpacking readline-common...
I: Unpacking ubuntu-keyring...
I: Configuring the base system...
I: Configuring readline-common...
I: Configuring liblz4-1:amd64...
I: Configuring gpgv...
I: Configuring libusb-0.1-4:amd64...
I: Configuring ubuntu-keyring...
I: Configuring libreadline6:amd64...
I: Configuring gcc-5-base:amd64...
I: Configuring gnupg...
I: Configuring libstdc++6:amd64...
I: Configuring libapt-pkg5.0:amd64...
I: Configuring apt...
I: Configuring libc-bin...
I: Base system installed successfully.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libcap-ng0 libdbus-1-3 libexpat1
Suggested packages:
  dbus-user-session | dbus-x11
The following NEW packages will be installed:
  dbus libcap-ng0 libdbus-1-3 libexpat1 libpam-systemd
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 501 kB of archives.
After this operation, 1762 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libexpat1 amd64 2.1.0-7 [71.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libcap-ng0 amd64 0.7.7-1 [10.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libdbus-1-3 amd64 1.10.6-1ubuntu3 [161 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/main amd64 dbus amd64 1.10.6-1ubuntu3 [141 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 libpam-systemd amd64 229-4ubuntu4 [116 kB]
Fetched 501 kB in 1s (454 kB/s)       
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libexpat1:amd64.
(Reading database ... 7251 files and directories currently installed.)
Preparing to unpack .../libexpat1_2.1.0-7_amd64.deb ...
Unpacking libexpat1:amd64 (2.1.0-7) ...
Selecting previously unselected package libcap-ng0:amd64.
Preparing to unpack .../libcap-ng0_0.7.7-1_amd64.deb ...
Unpacking libcap-ng0:amd64 (0.7.7-1) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../libdbus-1-3_1.10.6-1ubuntu3_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.6-1ubuntu3) ...
Selecting previously unselected package dbus.
Preparing to unpack .../dbus_1.10.6-1ubuntu3_amd64.deb ...
Unpacking dbus (1.10.6-1ubuntu3) ...
Selecting previously unselected package libpam-systemd:amd64.
Preparing to unpack .../libpam-systemd_229-4ubuntu4_amd64.deb ...
Unpacking libpam-systemd:amd64 (229-4ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu4) ...
Setting up libexpat1:amd64 (2.1.0-7) ...
Setting up libcap-ng0:amd64 (0.7.7-1) ...
Setting up libdbus-1-3:amd64 (1.10.6-1ubuntu3) ...
Setting up dbus (1.10.6-1ubuntu3) ...
Setting up libpam-systemd:amd64 (229-4ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for systemd (229-4ubuntu4) ...
‣ Installing Ubuntu complete.
‣ Assigning hostname...
‣ Assigning hostname complete.
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Cleaning dnf metadata...
‣ Cleaning yum metadata...
‣ Cleaning rpm metadata...
‣ Resetting machine ID...
‣ Resetting machine ID complete.
‣ Removing random seed...
‣ Removing random seed complete.
‣ Linking image file...
‣ Successfully linked /home/jlettman/test-mkosi-ubuntu/image.
‣ Resulting image size is 64.8M.
```
